# Generated by Django 4.1.5 on 2023-01-17 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_seller'),
        ('user', '0002_alter_profile_avatar_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cards',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='products.card'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='products.favorites'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sell_products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sell_products', to='products.product'),
        ),
    ]
