# Generated by Django 4.1.5 on 2023-01-17 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_profile_cards_remove_profile_favorites_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sell_products',
        ),
    ]
